spring.application.name=milap-api

spring.datasource.url=jdbc:mysql://localhost:3306/milap
spring.datasource.username=milap
spring.datasource.password=milap
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
